// +build autogen

// Package dockerversion is auto-generated at build-time
package dockerversion

// Default build-time variable for library-import.
// This file is overridden on build with build-time informations.
const (
	GitCommit          string = "18948"
	Version            string = "17.06.0-dev"
	BuildTime          string = "2018-10-13T07:36:10.628977239+00:00"
	IAmStatic          string = "true"
)

// AUTOGENERATED FILE; see /go/src/github.com/docker/docker/hack/make/.go-autogen
